name: SPM build & test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        destination:
          - 'platform=iOS Simulator,OS=15.0,name=iPhone 13'
          - 'platform=macOS,arch=x86_64'
          # - 'platform=macOS,arch=arm64' # Uncomment once https://github.com/actions/virtual-environments/issues/2187 resolved
        xcode: ['13.0', '13.1']
        os: ['macos-11']
    runs-on: ${{ matrix.os }}
    steps:
    - name: "Choose Xcode"
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcode }}
    - uses: actions/checkout@v2
    - name: Checkout LFS objects
      run: git lfs checkout
    - name: Build
      run: xcodebuild build -scheme Carpaccio -destination '${{matrix.destination}}'
  test:
    strategy:
      matrix:
        destination:
          - 'platform=macOS,arch=x86_64'
          # Uncomment / merge back to the `build` job once `exifdump` is separated to its own Package.swift
          # exifdump being a "tool" type target induces right now the following fail (with Xcode 13.1):
          # "unable to resolve product type 'com.apple.product-type.tool' for platform 'iphonesimulator"
          # - 'platform=iOS Simulator,OS=15.0,name=iPhone 13'
          # Uncomment once https://github.com/actions/virtual-environments/issues/2187 resolved
          # - 'platform=macOS,arch=arm64'
        xcode: ['13.0', '13.1']
        os: ['macos-11']
    runs-on: ${{ matrix.os }}
    steps:
    - name: "Choose Xcode"
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcode }}
    - uses: actions/checkout@v2
    - name: Checkout LFS objects
      run: git lfs checkout
    - name: Run tests
      run: xcodebuild test -scheme Carpaccio-Package -destination '${{matrix.destination}}'
