name: SPM build & test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Checkout LFS objects
      run: git lfs checkout
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
