name: SPM build & test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        destination:
          - 'platform=iOS Simulator,OS=13.1,name=iPhone 8'
          - 'platform=macOS,arch=arm64'
          - 'platform=macOS,arch=x86_64'
        xcode: ['13.1']
        os: ['macos-11']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcode }}
    - uses: actions/checkout@v2
    - name: Checkout LFS objects
      run: git lfs checkout
    - name: Build
      run: xcodebuild build -scheme Carpaccio-Package -destination ${{matrix.destination}}
    - name: Run tests
      run: xcodebuild test -scheme Carpaccio-Package -destination ${{matrix.destination}}
